# -*- coding: utf-8 -*-
"""Business_Demand_Factors_IT5113.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDaVXXq4-OW6iQ-w1NFjyxvOi55N8K5i
"""

# --- Step 1: Upload the CSV File ---
from google.colab import files
uploaded = files.upload()

# --- Step 2: Import Necessary Libraries ---
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt

# --- Step 3: Read the Dataset ---

df = pd.read_csv('business_demand_dataset_200.csv')


print("Dataset Preview:")
display(df.head())

# --- Step 4: Preprocessing ---

df['Has_Discount'] = df['Has_Discount'].map({'Yes': 1, 'No': 0})
df['Location'] = df['Location'].map({'Urban': 1, 'Rural': 0})


print("\nAfter Encoding:")
display(df.head())

# --- Step 5: T-test: Impact of Discount on Customer Numbers ---
discount_customers = df[df['Has_Discount'] == 1]['No_of_Customers']
no_discount_customers = df[df['Has_Discount'] == 0]['No_of_Customers']
t_stat, p_value = ttest_ind(discount_customers, no_discount_customers)

print(f"\nT-test Results:")
print(f"T-statistic = {t_stat:.4f}")
print(f"P-value = {p_value:.4f}")

if p_value < 0.05:
    print("Result: There is a significant difference in customer numbers based on discount offering.")
else:
    print("Result: No significant difference found.")

# --- Step 6: Linear Regression Model to Predict No_of_Customers ---

X = df[['Rating', 'Avg_Price', 'Has_Discount', 'Location']]
y = df['No_of_Customers']
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
print("\nLinear Regression Model Summary:")
print(model.summary())

# --- Step 7: Visualizations ---
import numpy as np

numeric_df = df.select_dtypes(include=[np.number])
plt.figure(figsize=(8,6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap (Numeric Features Only)')
plt.show()